#' Calculates day length (in hours) and the solar elevation above the
#' ecliptic plane based upon latitude and a day of year value.
#'
#' @param par: a vector of parameter values, this is functions specific
#' @param data: a nested list of data with one location:
#' 1. the date (doy or long format)
#' 2. the temperature data
#' 3. the photoperiod data (NA when not needed)
#' 4. a vector or matrix with necessary constants (NA when not needed)
#'    - long term mean temperature
#'    - latitude
#'    - etc...
#' 5. validation data (necessary!!)
#' @param model: the model name to be used in optimizing the model
#' Most models are listed in Melaas et al. 2013, additional ones
#' will be added over time, preliminary list:
#' 1. SEQ1.3
#' @keywords phenology, model, sequential
#' @export
#' @examples
#' rmse <- cost.function(par,data,model="SEQ1.3)
#'
#' # The cost function returns the rmse between the
#' # true values and those generated by the model given a
#' # parameterset par.

cost.function = function(par,data,model){

  # check if there is validation data
  if(length(data)!=5){
    stop("missing validation data, can't minimize cost function")
  }else{
    if(dim(data[[2]])[1] != length(data[[5]])){
      stop("incomplete validation data")
    }else{
      val = data[[5]]
      out = estimate.phenology(data = data,
                               model = "SEQ1.3",
                               par = par,
                               hpc = FALSE)
      # return the RMSE between the validation data and
      # the output of the model
      return(sqrt(sd((val - out)^2,na.rm=T)))
    }
  }
}
