#' phenocam_DB
#'
#' Data structure containing budburst dates for all deciduous broadleaf
#' (DB) sites included in the first PhenoCam data release. These data
#' are described in detail in Richardson et al. (2017)
#'
#' @format A structured list with 6 variables:
#' \describe{
#'   \item{site}{PhenoCam site name}
#'   \item{location}{geographic location}
#'   \item{doy}{DOY (1 - 365 as a vector)}
#'   \item{transition_dates}{budburst dates, as per 25 percent of the Gcc amplitude }
#'   \item{Ti}{mean daily temperature, matrix 365 rows x # site years columns}
#'   \item{Li}{daylength, matrix 365 rows x # site years columns}
#' }
"phenocam_DB"

#' phenocam_EN
#'
#' Data structure containing budburst dates for all evergreen needleleaf
#' (EN) sites included in the first PhenoCam data release. These data
#' are described in detail in Richardson et al. (2017)
#'
#' @format A structured list with 6 variables:
#' \describe{
#'   \item{site}{PhenoCam site name}
#'   \item{location}{geographic location}
#'   \item{doy}{DOY (1 - 365 as a vector)}
#'   \item{transition_dates}{budburst dates, as per 25 percent of the Gcc amplitude }
#'   \item{Ti}{mean daily temperature, matrix 365 rows x # site years columns}
#'   \item{Li}{daylength, matrix 365 rows x # site years columns}
#' }
"phenocam_EN"

#' phenocam_GR
#'
#' Data structure containing budburst dates for all grassland (GR)
#' sites included in the first PhenoCam data release. These data
#' are described in detail in Richardson et al. (2017)
#'
#' @format A structured list with 6 variables:
#' \describe{
#'   \item{site}{PhenoCam site name}
#'   \item{location}{geographic location}
#'   \item{doy}{DOY (1 - 365 as a vector)}
#'   \item{transition_dates}{budburst dates, as per 25 percent of the Gcc amplitude }
#'   \item{Ti}{mean daily temperature, matrix 365 rows x # site years columns}
#'   \item{Li}{daylength, matrix 365 rows x # site years columns}
#' }
"phenocam_GR"

#' igbp_1
#'
#' Raster mask of land cover density counts in 1x1 degree cells for the
#' conterminous US (CONUS). This data was generated by the
#' land_cover_density() function and it's default settings. The same dataset
#' can be generated with this function, but inclusion of the data in the
#' package saves some time. For areas outside the listed classes and CONUS
#' the function will have to be run again including a new source map and
#' destination grid.
#'
#' @format A raster layer with land cover density (0-1) for an igbp class:
#' \describe{
#'   \item{raster}{land cover density for igbp class 1}
#' }
"igbp_1"

#' igbp_4
#'
#' Raster mask of land cover density counts in 1x1 degree cells for the
#' conterminous US (CONUS). This data was generated by the
#' land_cover_density() function and it's default settings. The same dataset
#' can be generated with this function, but inclusion of the data in the
#' package saves some time. For areas outside the listed classes and CONUS
#' the function will have to be run again including a new source map and
#' destination grid.
#'
#' @format A raster layer with land cover density (0-1) for an igbp class:
#' \describe{
#'   \item{raster}{land cover density for igbp class 4}
#' }
"igbp_4"

#' igbp_5
#'
#' Raster mask of land cover density counts in 1x1 degree cells for the
#' conterminous US (CONUS). This data was generated by the
#' land_cover_density() function and it's default settings. The same dataset
#' can be generated with this function, but inclusion of the data in the
#' package saves some time. For areas outside the listed classes and CONUS
#' the function will have to be run again including a new source map and
#' destination grid.
#'
#' @format A raster layer with land cover density (0-1) for an igbp class:
#' \describe{
#'   \item{raster}{land cover density for igbp class 5}
#' }
"igbp_5"

#' igbp_10
#'
#' Raster mask of land cover density counts in 1x1 degree cells for the
#' conterminous US (CONUS). This data was generated by the
#' land_cover_density() function and it's default settings. The same dataset
#' can be generated with this function, but inclusion of the data in the
#' package saves some time. For areas outside the listed classes and CONUS
#' the function will have to be run again including a new source map and
#' destination grid.
#'
#' @format A raster layer with land cover density (0-1) for an igbp class:
#' \describe{
#'   \item{raster}{land cover density for igbp class 10}
#' }
"igbp_10"

