#' Flatten the format as generated by format_phenocam()
#' and format_modis(). Flattening the file format allows
#' for substantial speed increases in optimization however
#' limits readability. Using the split functionality between
#' the format_*() functions and this function allows for easy
#' subsetting of datasets.
#'
#' @param data: structure list generated by format_*() functions
#' @keywords phenology, model, preprocessing
#' @export

flat_format = function(data = NULL){

  if (is.null(data)){
    stop('please provide a structured list as generated by format_*() functions!')
  }

  # check if the element is flat by default
  if ("transition_dates" %in% names(data)){
    return(data)
  }

  # find the doy ranges as stored in the doy slot
  # of the first site
  doy = data[[1]]$doy

  # bind / calculate the photoperiod (daylength)
  # for all locations with do.call()
  Li = do.call("cbind",lapply(data,function(x)x$Li))

  # concat sitenames into a vector using a do.call()
  site = as.character(do.call("c",lapply(data,function(x){
    rep(x$site,ncol(x$Ti))
  })))

  # concat locations data into a matrix with the first row
  # being the latitude and the second longitude
  location = do.call("cbind",lapply(data,function(x){
    matrix(rep(x$location,ncol(x$Ti)),2,ncol(x$Ti))
  }))

  # concat all temperature data in one big matrix
  Ti = do.call("cbind",lapply(data,function(x)x$Ti))


  # concat all precip data in one big matrix
  Pi = do.call("cbind",lapply(data,function(x)x$Pi))

  # concat all temperature data in one big matrix
  # ltm = do.call("cbind",lapply(data,function(x)x$ltm))

  # long term mean
  ltm = matrix(NA,365,length(site))
  for (i in 1:length(site)){
    ltm[,i] = data[[which(names(data) == site[i])]]$ltm
  }

  # concat all transition dates for validatino into
  # a long vector
  transition_dates = as.vector(do.call("c",lapply(data,function(x)x$transition)))

  # recreate the validation data structure (new format)
  # but with concatted data
  data = list("site" = site,
              "location" = location,
              "doy" = doy,
              "transition_dates" = transition_dates,
              "ltm" = ltm,
              "Ti" = Ti,
              "Li" = Li,
              "Pi" = Pi)

  # return the formatted, faster data format
  return(data)
}
